import { z } from "zod";

export const ResearchInputSchema = z.object({
  topic: z.string().min(1, "topic is required").max(2000),
  conversationId: z.string().optional(),
  depth: z.enum(["quick", "standard", "deep"]).default("standard"),
});

export type ResearchInput = z.infer<typeof ResearchInputSchema>;

export interface ResearchResult {
  markdown: string;
  sources: string[];
  topic: string;
  ranAt: string;
}

/**
 * Step-2 placeholder for the LangGraph multi-agent system.
 *
 * Real graph (Step 3+): planner -> searchers (Tavily/web) -> synthesizer,
 * with Redis checkpointer + ws token streaming. For now we build a real
 * LangGraph StateGraph with the same input/output contract so apps/api and
 * apps/web can integrate once and the internals can be swapped without
 * touching callers.
 *
 * If OPENAI_API_KEY (or another chat model key) is present we still return
 * the deterministic template — wiring live LLM calls happens in Step 3.
 */
export async function runResearch(input: ResearchInput): Promise<ResearchResult> {
  const parsed = ResearchInputSchema.parse(input);
  const graph = await buildResearchGraph();
  const state = await graph.invoke({ topic: parsed.topic, depth: parsed.depth });
  return {
    markdown: state.markdown,
    sources: state.sources,
    topic: parsed.topic,
    ranAt: new Date().toISOString(),
  };
}

interface GraphState {
  topic: string;
  depth: string;
  markdown: string;
  sources: string[];
}

// Lightweight stand-in for a compiled LangGraph StateGraph. We import the
// real library lazily so the package builds even when langchain peers
// resolve differently across bun/npm, and so Step 3 can replace this body
// with `new StateGraph(...)` without changing the exported signature.
async function buildResearchGraph(): Promise<{
  invoke: (s: Pick<GraphState, "topic" | "depth">) => Promise<GraphState>;
}> {
  try {
    await import("@langchain/langgraph");
    await import("@langchain/core/messages");
  } catch {
    // Optional peer — the stub graph below does not need it to run.
  }

  return {
    invoke: async ({ topic, depth }) => ({
      topic,
      depth,
      sources: [],
      markdown: templateReport(topic, depth),
    }),
  };
}

function templateReport(topic: string, depth: string): string {
  const safe = topic.trim().slice(0, 200);
  return `# Research: ${safe}\n\n> Depth: **${depth}** · generated by the Step-2 stub graph. Live multi-agent search lands in Step 3.\n\n## Summary\n\nThis is a placeholder report so the full loop (web → api → agent → postgres → web) works end-to-end before real agents exist.\n\n## Key points\n\n- **Topic received**: ${safe}\n- **Next**: planner + searcher + synthesizer nodes with citations\n- **Streaming**: progress + tokens will flow over websockets (see \`apps/api/src/ws.ts\`)\n\n## Suggested outline for the real run\n\n1. Define scope and questions\n2. Gather sources (web + docs)\n3. Synthesize with citations\n4. Return markdown + source list\n\n## Sources\n\n- _none yet — stub run_\n`;
}

export const agentInfo = {
  name: "@repo/agent",
  graph: "research-stub-v0",
  streaming: false,
  note: "Replace buildResearchGraph() with a real StateGraph in Step 3.",
};
